### ISSUE TITLE
ImagePullBackOff?

### ISSUE THREAD

**Issue by jordan-da** [smallstep/autocert#120]
### Subject of the issue
When following the helm instructions, all the pods result in `ImagePullBackOff` statuses. I didn't notice a step to authenticate with a a private repo or anything, does this project require enterprise support to use?

### Environment
GKE 1.23

### Steps to reproduce
` helm -n autocert install autocert smallstep/autocert`

### Expected behaviour
The images pull down correctly

### Actual behaviour
```
14:08:21 ▶ kubectl get pod -n autocert
NAME                           READY   STATUS             RESTARTS   AGE
autocert-696d9c6f78-fdzs5      0/1     ImagePullBackOff   0          3m58s
autocert-7b658fb6cb-jwhl9      0/1     ImagePullBackOff   0          120m
autocert-step-certificates-0   0/1     ImagePullBackOff   0          120m
```

**Comment by maraino** [comment]
Hi, we have a DNS problem with cr.step.sm. As a fallback you can use `smallstep/autocert*`:
```yaml
autocert:
  image:
    repository: smallstep/autocert-controller
bootstrapper:
  image:
    repository: smallstep/autocert-bootstrapper
renewer:
  image:
    repository: smallstep/autocert-renewer
```
