### ISSUE TITLE
This does not run on RPI (aarm64)

### ISSUE THREAD

**Issue by blmhemu** [smallstep/autocert#15]
### What would you like to be added
Support for aarm64

default          pod/autocert-step-certificates-0             0/1     CrashLoopBackOff   6          9m13s
default          pod/autocert-854c8956dd-mp7j5                0/1     Running            6          9m13s
default          pod/autocert-lg46f                           0/1     Error              0          9m13s
default          pod/autocert-wgrqd                           0/1     Error              0          7m40s
default          pod/autocert-l6crm                           0/1     Error              0          6m32s
default          pod/autocert-mtz2z                           0/1     Error              0          5m52s

Looks like one or two containers might be running but others are failing.

**Comment by dopey** [comment]
Thanks @fastlorenzo! Going to close this, but please reopen if you're still finding an issue.

**Comment by gclawes** [comment]
I'm seeing this on rpi4:
```ubuntu@pi01:~$ uname -a
Linux pi01.pico 5.4.0-1015-raspi #15-Ubuntu SMP Fri Jul 10 05:34:24 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
ubuntu@pi01:~$ sudo docker run -it --rm smallstep/autocert-controller:0.12.2
standard_init_linux.go:211: exec user process caused "exec format error"
```

It looks like there are not arm64 images on dockerhub: https://hub.docker.com/r/smallstep/autocert-controller/tags

**Comment by fastlorenzo** [comment]
FYI, I've built and published docker images that support ARM on docker hub: https://hub.docker.com/r/fastlorenzo/autocert-controller

**Comment by dopey** [comment]
@fastlorenzo @gclawes Sounds like we need aarm64 (& others) builds of auto-cert, not just `certificates`. I'll go ahead and re-open this one.

Hopefully it's not too difficult to port over the `buildx` stuff that we've got doing this in `certificates`.

**Comment by fastlorenzo** [comment]
@dopey I've actually rebuilt all docker images with arm support:
- https://hub.docker.com/r/fastlorenzo/autocert-init
- https://hub.docker.com/r/fastlorenzo/autocert-controller
- https://hub.docker.com/r/fastlorenzo/autocert-bootstrapper
- https://hub.docker.com/r/fastlorenzo/autocert-renewer
- https://hub.docker.com/r/fastlorenzo/step-ca-bootstrap

**Comment by fastlorenzo** [comment]
FYI I did it with GitHub workflow leveraging buildx: https://www.github.com/fastlorenzo/autocert/tree/master/.github%2Fworkflows

**Comment by maraino** [comment]
@fastlorenzo wow, thanks for creating those workflows, we don't have yet experience with GitHub workflows, but we might integrate them in autocert.

**Comment by fastlorenzo** [comment]
Awesome, looking forward to have arm support in official docker builds :)

**Comment by dopey** [comment]
Update all Dockerfiles to most recent cli version. Hopefully that's the fix.

**Comment by dopey** [comment]
https://github.com/smallstep/autocert/blob/master/controller/Dockerfile
https://github.com/smallstep/autocert/blob/master/bootstrapper/Dockerfile
https://github.com/smallstep/autocert/blob/master/renewer/Dockerfile
https://github.com/smallstep/autocert/blob/master/init/Dockerfile

**Comment by dopey** [comment]
https://github.com/smallstep/autocert/blob/master/init/Dockerfile#L14

**Comment by dopey** [comment]
Hey @blmhemu our thinking is that most of the issue is the v0.14.2 of cli hardcoded in a number of different files that I listed above. We're wondering if changing that to v0.15.3 and also updating the autocert/init dockerfile to use the correct linux distro (`amd64`, `arm`, etc.).

If anyone has an arm kubernetes cluster and can test if this would work, we'd be very appreciative.

**Comment by gclawes** [comment]
I've got an RPI cluster I can test with.

**Comment by tiagoposse** [comment]
I can confirm the following values work are able to provision certs on an arm64 k3s cluster:
```
step-certificates:
  image:
    tag: 0.15.4

autocert:
  image:
    repository: fastlorenzo/autocert-controller
    tag: latest
    pullPolicy: IfNotPresent

bootstrapper:
  image:
    repository: fastlorenzo/autocert-bootstrapper
    tag: latest
    pullPolicy: IfNotPresent

renewer:
  image:
    repository: fastlorenzo/autocert-renewer
    tag: latest
    pullPolicy: IfNotPresent
```

**Comment by tiagoposse** [comment]
I can confirm that I was able to deploy autocert and issue certs successfully using @fastlorenzo images.

My values.yml file looks like this:
```
step-certificates:
  image:
    tag: 0.15.4

autocert:
  image:
    repository: fastlorenzo/autocert-controller
    tag: latest

bootstrapper:
  image:
    repository: fastlorenzo/autocert-bootstrapper
    tag: latest

renewer:
  image:
    repository: registry.tiagoposse.com/autocert-renewer
    tag: latest
```
