### ISSUE TITLE
autocert doesn't create certificates for kubernetes statefulset workloads

### ISSUE THREAD

**Issue by etfeet** [smallstep/autocert#3]
### Subject of the issue
kubernetes StatefulSet do not get certificates requested / deployed to the pod

### Environment
Kubernetes version:
client: 1.15.4
server: 1.12.8
Cloud provider or hardware configuration:
gke
* OS (e.g., from /etc/os-release):
Centos 7
* Kernel (e.g., `uname -a`):
Linux elasticsearch-master-0 4.14.127+ #1 SMP Tue Jun 18 23:08:40 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux

Install tools:
helm

### Steps to reproduce
helm repo add elastic https://helm.elastic.co
wget -4 https://raw.githubusercontent.com/elastic/helm-charts/master/elasticsearch/values.yaml
edit values.yaml and add autocert.step.sm/name: test123.default.svc.cluster.local to podAnnotations key

helm install --name elasticsearch elastic/elasticsearch

### Expected behaviour
cert gets issued and deployed to the pod

### Actual behaviour
cert is neither issued nor deployed to the pod

### Additional context
kubectl describe pod elasticsearch-master-0
Name:           elasticsearch-master-0
Namespace:      kubeprod
Priority:       0
Node:           gke-apollo-default-pool-3fc7c75e-hll3/10.138.15.221
Start Time:     Wed, 25 Sep 2019 21:26:38 +0000
Labels:         app=elasticsearch-master
                chart=elasticsearch
                controller-revision-hash=elasticsearch-master-78644d5858
                heritage=Tiller
                release=elasticsearch
                statefulset.kubernetes.io/pod-name=elasticsearch-master-0
Annotations:    autocert.step.sm/name: test123.kubeapps.svc.cluster.local
                configchecksum: 3c3d7b85a691a47a1dc120aa0ec8135f70fe1471cd12803212bfef7e83cf931
Status:         Running

kubectl exec -it elasticsearch-master-0 ls /var/run/
blkid    cryptsetup  lock  secrets   setrans  user
console  faillock    log   sepermit  systemd  utmp

However, both autocert and the smallstep ca logs don't have any entries for requesting/issueing any certificates.

**Comment by maraino** [comment]
@etfeet Can you check that you've enabled the label in the desired namespace? For example:
```sh
$ kubectl get namespace -L autocert.step.sm
NAME                   STATUS   AGE    AUTOCERT.STEP.SM
default                Active   3d3h   enabled
...
```
If it's not just simply do:
```sh
kubectl label namespace default autocert.step.sm=enabled
```
You can see more details [here](https://github.com/smallstep/autocert#usage)

I've checked with the most simple statefulset that I can think and it worked properly:
```sh
$ kubectl apply -f /tmp/stateful.yaml
statefulset.apps/test created
$ kubectl exec test-0 -- ls -l /var/run/autocert.step.sm
Defaulting container name to busybox.
Use 'kubectl describe pod/test-0 -n default' to see all of the containers in this pod.
total 12
-rw-------    1 root     root           599 Sep 25 23:06 root.crt
-rw-r--r--    1 root     root          1486 Sep 25 23:06 site.crt
-rw-r--r--    1 root     root           227 Sep 25 23:06 site.key
```
Here is my yaml
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  serviceName: test
  template:
    metadata:
      annotations:
        autocert.step.sm/name: test.default.svc.cluster.local
      labels:
        app: test
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: busybox
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sleep", "300"]
```

Can you check that your statefulset has the annotation in the right place? See my example.
