### ISSUE TITLE
Boostrapper keeps failing due to missing secret

### ISSUE THREAD

**Issue by alieniasty** [smallstep/autocert#60]
### Subject of the issue
I'm using autocert in 3 of my pods. In 2 of them everything works great, the cert is injected into the container with no problems, however in one of them (the only one that has custom init containers) I'm constantly getting `Error: secret "podname-d8dt8" not found` error.

From the _kubectl describe pod_ I see:

`STEP_TOKEN:        <set to the key 'token' in secret 'podname-d8dt8'>  Optional: false`

for autocert-bootstrapper container.

In my main container I have:

`/var/run/secrets/kubernetes.io/serviceaccount from podname-token-629hw (ro)`

The only difference between working pods and the one that keeps failing is the one that keeps failing has a custom ServiceAccount assigned that is named exactly after the pod. Here is the config for ServiceAccount:
```

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: podname
subjects:
- kind: ServiceAccount
  name: podname
  namespace: $NAMESPACE
roleRef:
  kind: Role
  name: podname
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: podname
  namespace: $NAMESPACE
  labels:
    app: podname
rules:
- apiGroups: ["*"]
  resources:
  - jobs
  - jobs/status
  - pods
  - deployments
  - deployments/status 
  verbs:
  - get
  - watch
  - list
  - status
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podname
  namespace: $NAMESPACE
  labels:
    app: podname
---
```

### Environment
* Kubernetes version: 1.20.15
* Cloud provider or hardware configuration: EKS

**Comment by maraino** [comment]
Hi @alieniasty, Can you provide a full yaml that I can execute test your use case, for example, this deployment with an init container and service account works as exected:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-mtls
subjects:
- kind: ServiceAccount
  name: hello-mtls
  namespace: default
roleRef:
  kind: Role
  name: hello-mtls
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hello-mtls
  namespace: default
  labels:
    app: hello-mtls
rules:
- apiGroups: ["*"]
  resources:
  - jobs
  - jobs/status
  - pods
  - deployments
  - deployments/status 
  verbs:
  - get
  - watch
  - list
  - status
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-mtls
  namespace: default
  labels:
    app: hello-mtls
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hello-mtls
  labels: 
    app: hello-mtls
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: hello-mtls
  template:
    metadata:
      annotations:
        autocert.step.sm/name: hello-mtls.default.svc.cluster.local
        autocert.step.sm/sans: hello-mtls.default.svc.cluster.local,127.0.0.1
      labels:
        app: hello-mtls
    spec:
      serviceAccountName: hello-mtls
      initContainers:
        - name: alpine
          image: "alpine:latest"
          command: [
            "/bin/sh", "-c", "echo hello from alpine"
          ]
      containers:
      - name: hello-mtls
        image: smallstep/hello-mtls-server-go:latest
```

**Comment by alieniasty** [comment]
Thanks for such a quick response. The following manifest after necessary obfuscation pretty much sums up my deployment.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: podname
  name: podname
  namespace: namespacename
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: podname
  name: podname
  namespace: namespacename
rules:
- apiGroups:
  - '*'
  resources:
  - jobs
  - jobs/status
  - pods
  - deployments
  - deployments/status
  verbs:
  - get
  - watch
  - list
  - status
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: podname
  namespace: namespacename
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podname
subjects:
- kind: ServiceAccount
  name: podname
  namespace: namespacename
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations: {}
  labels: {}
  name: podname-env
---
apiVersion: v1
kind: Service
metadata:
  name: podname
  namespace: namespacename
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: podname
    branch: namespacename
    release: podname
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: podname
    build: namespacename
    release: podname
  name: podname
  namespace: namespacename
spec:
  progressDeadlineSeconds: 7200
  replicas: 1
  selector:
    matchLabels:
      app: podname
      release: podname
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        autocert.step.sm/name: podname
      labels:
        app: podname
        branch: namespacename
        build: namespacename
        release: podname
    spec:
      containers:
      - env:
        - name: password1
          valueFrom:
            secretKeyRef:
              key: password1
              name: app-secrets
        - name: password2
          valueFrom:
            secretKeyRef:
              key: password2
              name: app-secrets
        - name: password3
          valueFrom:
            secretKeyRef:
              key: password3
              name: app-secrets
        - name: password4
          valueFrom:
            secretKeyRef:
              key: password4
              name: app-secrets
        - name: password5
          valueFrom:
            secretKeyRef:
              key: password5
              name: app-secrets
        envFrom:
        - configMapRef:
            name: podname-env
        image: docker.blabla.io/myimage
        imagePullPolicy: Always
        name: podname
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        resources:
          limits:
            memory: 8500Mi
          requests:
            cpu: 2400m
            memory: 5100Mi
      hostAliases:
      - hostnames:
        - myhostname.blabla.io
        ip: <some ip>
      imagePullSecrets:
      - name: artifactsrepo
      initContainers:
      - args:
        - |
          sleep 30 # wait for DB seed job to be created
          if [ $(curl -o /dev/null -s -w "%{http_code}\n" -X GET --cacert ${SERVICEACCOUNT}/ca.crt --header "Authorization: Bearer $(cat ${SERVICEACCOUNT}/token)" ${APISERVER}/apis/batch/v1/namespaces/namespacename/jobs/podname-db-setup) != "200" ]; then
            echo Could not find DB seed job. Aborting.
            exit 0 # Handle cases for the env without db seed job
          fi
          while [ $(curl -s -X GET --cacert ${SERVICEACCOUNT}/ca.crt --header "Authorization: Bearer $(cat ${SERVICEACCOUNT}/token)" ${APISERVER}/apis/batch/v1/namespaces/namespacename/jobs/podname-db-setup/status | jq .status.succeeded ) != "1" ]
          do
            echo DB seed job has not succeeded yet
            if [ $(curl -s -X GET --cacert ${SERVICEACCOUNT}/ca.crt --header "Authorization: Bearer $(cat ${SERVICEACCOUNT}/token)" ${APISERVER}/apis/batch/v1/namespaces/namespacename/jobs/podname-db-setup/status | jq .status.failed ) == "1" ]; then
              echo DB seed job failed
              exit 0 # Handle cases for the env with manual db seed
            fi
            sleep 15
          done
          echo DB seed has been succeeded
        command:
        - /bin/sh
        - -c
        env:
        - name: APISERVER
          value: https://kubernetes.default.svc
        - name: SERVICEACCOUNT
          value: /var/run/secrets/kubernetes.io/serviceaccount
        image: docker.artifactsrepo.blabla.io/alpine-curl-jq
        name: wait-for-podname-db-setup-job
      serviceAccountName: podname
      volumes:
      - name: private-storage
        persistentVolumeClaim:
          claimName: private-storage
      - name: public-storage
        persistentVolumeClaim:
          claimName: public-storage
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: podname-namespacename
  namespace: namespacename
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: podname
  targetCPUUtilizationPercentage: 50
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: podnamepolicy-namespacename
  namespace: namespacename
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: otherpod1
    - podSelector:
        matchLabels:
          app: otherpod2
    - podSelector:
        matchLabels:
          app: otherpod3
    - podSelector:
        matchLabels:
          app: otherpod4
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: otherpod1
    - podSelector:
        matchLabels:
          app: otherpod2
    - podSelector:
        matchLabels:
          app: otherpod3
    - podSelector:
        matchLabels:
          app: otherpod4
  podSelector:
    matchLabels:
      app: podname
  policyTypes:
  - Ingress
  - Egress
```

To be honest I'm running out of ideas where should I look.
